defaults: &defaults
  tmpPath: 'tmp'
  sassCache: 'tmp/.sass-cache'
  cacheFile: 'tmp/.files.json'
  pkgBuiltTrackFile: 'tmp/.packages.json'
  filerevFile: 'tmp/.filerev.json'
  manifestFile: 'tmp/.manifest.json'
  manifestSrcCwd: 'tmp/dummy'
  manifestDestCwd: 'tmp/dummy'
  pkgClassPaths:
    - "dummy/pkg"

development:
  <<: *defaults